//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;ResourceDictionary
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///     xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;!-- Main Window--&gt;
        ///    &lt;system:String x:Key=&quot;WelcomeToEasySave&quot;&gt;Welcome to EasySave by Prosoft&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;RunBackupJob&quot;&gt;Run a backup job&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;ManageBackupJobs&quot;&gt;Manage backup jobs&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;NewBac [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Dictionary_en_En {
            get {
                return ResourceManager.GetString("Dictionary_en_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;ResourceDictionary 
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot; 
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot; 
        ///     xmlns:system=&quot;clr-namespace:System;assembly=mscorlib&quot;&gt;
        ///
        ///    &lt;!-- Main Window--&gt;
        ///    &lt;system:String x:Key=&quot;WelcomeToEasySave&quot; &gt;Bievenue sur EasySave par Prosoft&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;RunBackupJob&quot; xml:space=&quot;preserve&quot;&gt;Lancer un travail&amp;#13;de sauvegarde&lt;/system:String&gt;
        ///    &lt;system:String x:Key=&quot;ManageBackupJobs&quot; xml:space=&quot;preserve&quot;&gt;G [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Dictionary_fr_Fr {
            get {
                return ResourceManager.GetString("Dictionary_fr_Fr", resourceCulture);
            }
        }
    }
}
